# -*- coding: utf-8 -*-
"""origin_validation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/tnc-br/ddf-insights-analytics/blob/main/origin_validation.ipynb

**Meta Data and Parameters**
"""

#@title Parameters
lat = -9
lon = -40
oxygen_measurements = [32,33,34]
nitrogen_measurements = [22,23,24]
carbon_measurements = [-20,-21,-23]


"""Requirements"""

#Install requirements
# !pip install geemap

"""Libraries"""

#Import Libraries
import ee
import os
import numpy as np
import scipy

"""Global Variable definition"""

isoscapes_ee_path = 'users/kazob/isoscapes'
oxygen_means_iso = None
oxygen_variances_iso = None
carbon_means_iso = None
carbon_variances_iso = None
nitrogen_means_iso = None
nitrogen_variances_iso = None
poi = None


class ttest():
    


  """Authentication and Authorization"""
  def initialize(self):
    #Authenticate
    if os.path.isfile('key.json') :

        # connection to the service account
        service_account = 'fraud-detection-pipeline-sa@kazob-370920.iam.gserviceaccount.com'
        credentials = ee.ServiceAccountCredentials(service_account, 'key.json')
        ee.Initialize(credentials)
        print('initialized with key')

    # if in local env use the local user credential
    else:
        ee.Initialize()


    """fetching isoscapes"""

    parent_asset = ee.data.getAsset(isoscapes_ee_path)
    parent_id = parent_asset['name']
    parent_type = parent_asset['type']
    asset_list = []
    child_assets = ee.data.listAssets({'parent': parent_id})['assets']
    for child_asset in child_assets:
        child_id = child_asset['name']
        child_type = child_asset['type']
        if child_type in ['FOLDER','IMAGE_COLLECTION']:
            # Recursively call the function to get child assets
            asset_list.extend(get_asset_list(child_id))
        else:
            asset_list.append(child_id)
    asset_list

    for asset in asset_list:
      if ('oxygen' in asset) and ('mean' in asset):
        oxygen_means_iso = ee.Image(asset)
      elif 'oxygen' in asset and 'variance' in asset:
        oxygen_variances_iso = ee.Image(asset)
      elif 'd13C' in asset:
        carbon_means_iso = ee.Image(asset)
        carbon_variances_iso = ee.Image(asset).select('b1')
      elif 'd15N' in asset and 'SD' in asset:
        nitrogen_variances_iso = ee.Image(asset)
      elif 'd15N' in asset and 'SD' not in asset:
        nitrogen_means_iso = ee.Image(asset)

    #carbon_means_iso.getInfo()

  def ttest(self):
    """POI definition"""

    poi = ee.Geometry.Point(lon,lat)

    """***Oxygen***

    Isoscape
    """

    isoscape_mean = oxygen_means_iso.reduceRegion(
      reducer = ee.Reducer.mean(),
      geometry = poi,
      scale = 30).getInfo().get('b1');
    isoscape_var = oxygen_variances_iso.reduceRegion(
      reducer = ee.Reducer.mean(),
      geometry = poi,
      scale = 30).getInfo().get('b1');
    if isoscape_var is not None:
      isoscape_std = np.sqrt(isoscape_var)
    else:
      isoscape_std = 0

    """Isotope calculation"""

    isotope_mean = np.mean(oxygen_measurements)
    isotope_std = np.std(oxygen_measurements)
    print(isotope_mean,isotope_std, isoscape_mean, isoscape_std)

    """ttest and p-value"""

    _, p_value_oxygen = scipy.stats.ttest_ind_from_stats(
                isotope_mean, isotope_std, len(oxygen_measurements), isoscape_mean, isoscape_std, 30, equal_var=False, alternative="two-sided")

    """**Carbon**

    Isoscape
    """

    ###DELETE
    carbon_means_iso = oxygen_means_iso
    carbon_variances_iso = oxygen_variances_iso
    #delete
    isoscape_mean = carbon_means_iso.reduceRegion(
      reducer = ee.Reducer.mean(),
      geometry = poi,
      scale = 30).getInfo().get('b1');
    isoscape_var = carbon_variances_iso.reduceRegion(
      reducer = ee.Reducer.mean(),
      geometry = poi,
      scale = 30).getInfo().get('b1');
    if isoscape_var is not None:
      isoscape_std = np.sqrt(isoscape_var)
    else:
      isoscape_std = 0

    """Isotope calculation"""

    isotope_mean = np.mean(carbon_measurements)
    isotope_std = np.std(carbon_measurements)
    print(isotope_mean,isotope_std, isoscape_mean, isoscape_std)

    """ttest and p-value"""

    _, p_value_carbon = scipy.stats.ttest_ind_from_stats(
                isotope_mean, isotope_std, len(carbon_measurements), isoscape_mean, isoscape_std, 30, equal_var=False, alternative="two-sided")

    """**Nitrogen**

    Isoscape
    """

    isoscape_mean = nitrogen_means_iso.reduceRegion(
      reducer = ee.Reducer.mean(),
      geometry = poi,
      scale = 30).getInfo().get('b1');
    isoscape_var = nitrogen_variances_iso.reduceRegion(
      reducer = ee.Reducer.mean(),
      geometry = poi,
      scale = 30).getInfo().get('b1');
    if isoscape_var is not None:
      isoscape_std = np.sqrt(isoscape_var)
    else:
      isoscape_std = 0

    """Isotope calculation"""

    isotope_mean = np.mean(nitrogen_measurements)
    isotope_std = np.std(nitrogen_measurements)
    print(isotope_mean,isotope_std, isoscape_mean, isoscape_std)

    """ttest and p-value"""

    _, p_value_nitrogen = scipy.stats.ttest_ind_from_stats(
                isotope_mean, isotope_std, len(nitrogen_measurements), isoscape_mean, isoscape_std, 30, equal_var=False, alternative="two-sided")

    """Origin Verification"""

    origin_validity = p_value_oxygen * p_value_carbon * p_value_nitrogen
    return origin_validity;