# name: Docker

# on:
#   push:
#     branches: [ main ]

# jobs:

#     deploy:

#         name: Setup Gcloud Account
#         runs-on: ubuntu-latest
#         env:
#           IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
#         steps:

#         - name: Login
#           uses: google-github-actions/setup-gcloud@v0
#           with:
#             project_id: ${{ secrets.GCP_PROJECT_ID }}
#             service_account_email: ${{ secrets.GCP_EMAIL }}
#             service_account_key: ${{ secrets.GCP_CREDENTIALS }}

#         - name: Configure Docker
#           run: gcloud auth configure-docker --quiet

#         - name: Checkout repository
#           uses: actions/checkout@v2

#         - name: Build Docker image
#           run: docker build . -t $IMAGE_NAME

#         #- name: Test Docker image -- Please add unit test
#         #  run: docker run $IMAGE_NAME sh -c "pip main.py"

#         - name: Push Docker image
#           run: docker push $IMAGE_NAME

#         - name: Deploy Docker image
#           run: gcloud run deploy ${{ secrets.GCP_APP_NAME }} --image $IMAGE_NAME --region us-central1 --platform managed
          
name: Deployment

# on commit push, run job
on: [push]

jobs:
  run:
    # worker runs on latest ubuntu
    runs-on: ubuntu-latest
#     steps:
#         # checkout to our repository so we have access to the source code
#         - uses: actions/checkout@v2

#         # the actual deployment to google
#         - name: Cloud Functions Deploy
#           uses: google-github-actions/deploy-cloud-functions@v0.1.2
#           with:
#             credentials: ${{ secrets.GCP_CREDENTIALS }}
#             name: hello_cloud_functions
#             description: Test python cloud function # nullable
#             project_id: ${{ secrets.GCP_PROJECT_ID }}
#             region: us-east1
#             #source_dir: .
#             # name of our function in our main.py file, defaults to the resource name suffix 
#             entry_point: hello_firestore
#             # runtime to use for the function
#             runtime: python311
#             # the function execution timeout
#             timeout: 60
#             # the maximum number of instances for the function.
#             max_instances: 1
#             # optional configs, see google-cloud-actions/deploy-cloud-functions for full reference
#             # list of key-value pairs to set as environment variables in the form KEY1=VALUE1,KEY2=VALUE2.#       env_vars: # optional
#             event_trigger_resource: "projects/kazob-370920/locations/us-east1/triggers/fraud-detection-231413"
#             event_trigger_type: "google.cloud.firestore.document.v1.created"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.DEV_GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.DEV_GCP_EMAIL }}
        service_account_key: ${{ secrets.DEV_GCP_CREDENTIALS }}
    
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v0
 
    - name: Use gcloud CLI
      run: gcloud info
    
    - name: 'Use to deploy a cloud function gen 2: fraud-detection-old-version'
      run: gcloud functions deploy fraud-detection-old-version-sc --gen2 --runtime=python311 --source=./fraud-detection-old-version --region=southamerica-east1 --entry-point=hello_firestore --trigger-event-filters='type=google.cloud.firestore.document.v1.written' --trigger-event-filters='database=(default)' --trigger-event-filters-path-pattern='document=untrusted_samples/{pushId}' --trigger-location=southamerica-east1 --trigger-service-account='843836318122-compute@developer.gserviceaccount.com' 
      #--trigger-resource='projects/kazob-370920/databases/(default)/documents/untrusted_samples/{pushId}'
      #--trigger-topic=eventarc-us-east1-fraud-detection-231413-297
    
    - name: 'Use to deploy a cloud function gen 2: fraud-detection-update-sample'
      run: gcloud functions deploy fraud-detection-update-sample-sc --gen2 --runtime=python311 --source=./fraud-detection-update-sample --region=southamerica-east1 --entry-point=hello_firestore --trigger-event-filters='type=google.cloud.firestore.document.v1.written' --trigger-event-filters='database=(default)' --trigger-event-filters-path-pattern='document=untrusted_samples/{pushId}' --trigger-location=southamerica-east1 --trigger-service-account='843836318122-compute@developer.gserviceaccount.com' 
    
    - name: 'Use to deploy a cloud function gen 2: Firestore-Earth-Engine-ETL'
      run: gcloud functions deploy Firestore-Earth-Engine-ETL-sc --gen2 --runtime=python311 --source=./Firestore-Earth-Engine-ETL --region=southamerica-east1 --entry-point=etl --trigger-http
    
    - name: 'Use to deploy a cloud function gen 2: fraud-detection-new-isoscape'
      run: gcloud functions deploy fraud-detection-new-isoscape-sc --gen2 --runtime=python311 --source=./fraud-detection-new-isoscape --region=southamerica-east1 --entry-point=reevaluate --trigger-http
        
    - name: 'Use to deploy a cloud function gen 2: update-org-ee-auto-auth'
      run: gcloud functions deploy update-org-ee-auto-auth-sc --gen2 --runtime=python311 --source=./update-org-ee-auto-auth --region=southamerica-east1 --entry-point=update_ee_acl --trigger-event-filters='type=google.cloud.firestore.document.v1.written' --trigger-event-filters='database=(default)' --trigger-event-filters-path-pattern='document=organizations/{pushId}' --trigger-location=southamerica-east1 --trigger-service-account='843836318122-compute@developer.gserviceaccount.com' 
        
    - name: 'Use to deploy a cloud function gen 2: user-update-iam-check'
      run: gcloud functions deploy user-update-iam-check-sc --gen2 --runtime=python311 --source=./user-update-iam-check --region=southamerica-east1 --entry-point=grant_access --trigger-event-filters='type=google.cloud.firestore.document.v1.written' --trigger-event-filters='database=(default)' --trigger-event-filters-path-pattern='document=users/{pushId}' --trigger-location=southamerica-east1 --trigger-service-account='843836318122-compute@developer.gserviceaccount.com' 

    - name: 'Use to deploy a cloud function gen 2: fraud-detection-generate-maps'
      run: gcloud functions deploy fraud-detection-generate-maps --gen2 --runtime=python311 --source=./fraud-detection-generate-maps --region=southamerica-east1 --entry-point=hello_pubsub --trigger-topic=fraud-detection-generate-maps-daily --trigger-service-account='fraud-detection-maps-trigger@river-sky-386919.iam.gserviceaccount.com'